language: vim
# trusty has cmake >= 2.8.12
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    packages:
    - g++-4.7
    - cmake

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script:
    - vim -Nu 'test/.vimrc' -c 'Vader! test/cmake.vader'
    - vim -Nu 'test/.vimrc' -c 'let g:cmake_config_in_quickfix = 1 | Vader! test/cmake.vader'
    - vim -Nu 'test/.vimrc' -c 'let g:cmake_config_in_quickfix = 1 | Vader! test/cmake_quickfix.vader'
