os: Visual Studio 2015

install:
  - cinst vim
  - cinst cmake
  - set PATH=%PATH%;C:\Program Files\CMake\bin
  - git clone https://github.com/junegunn/vader.vim

build_script:
  - vim -Nu test/.vimrc -c 'Vader! test/cmake.vader' --not-a-term
  - vim -Nu 'test/.vimrc' --cmd 'let g:cmake_config_in_quickfix = 1' -c 'Vader! test/cmake_quickfix.vader' --not-a-term
  - vim -Nu 'test/.vimrc' --cmd 'let g:cmake_config_in_quickfix = 1' -c 'Vader! test/cmake.vader' --not-a-term
